spring.application.name=VigiLance


spring.datasource.url=jdbc:postgresql://localhost:5432/VigiLanceDB
spring.datasource.username=postgres
spring.datasource.password=af1c625a648e4bf2937b55f6df64fa12
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# URL de base pour Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Activer Swagger UI
springdoc.swagger-ui.enabled=true
# Désactiver le tri des endpoints (optionnel)
springdoc.swagger-ui.operationsSorter=method
# Nom de l'application dans Swagger
springdoc.info.title=VigiLance API